### ISSUE TITLE
BUGS : 게시물 상세조회 시 likeStatus의 형이 boolean이 아닌 숫자로 출력되는 ERROR

### ISSUE THREAD

**Issue by sumin-dev** [moodCatcherProject/Back-End#105]
### 한 일
- 게시물 상세 조회 API에서 **likeStatus**가 숫자로 출력되는 에러 발생.
 ![image](https://user-images.githubusercontent.com/109029407/189281381-7078a4b4-f5d7-44a9-9793-f0297280e69e.png)

- Like를 누르면 **likeStatus는 true**로 값이 전송되고 **mysql DB**에서는 tinyint로 값이 변환되어 **0(false) 또는 1(true)** 로 저장.
- likeStatus를 조회하는 다른API(게시물 전체 조회)에서는 likeStatus 값이 boolean으로 출력되므로 **mysql의 문제는 아니라고 판단**.
 ![image](https://user-images.githubusercontent.com/109029407/189281457-9d4e2044-fcc9-46f4-9403-9ce423828085.png)

### 에러 내용
- **게시물 상세 조회API**에서 사용하는 likeStatus 코드
```cmd
const findPostDetailWithLikeStatus = async (postId, userId) => {
    const post = await Post.findOne({
        where: { postId },
        attributes: { exclude: ['gender'] },
        raw: true,
        include: [
            {
                model: Like,
                where: { postId, userId },
                attributes: ['likeStatus'],
                raw: true
            }
        ]
    });

    return post;
};
```

- **게시물 전체 조회API**에서 사용하는 likeStatus 코드
```cmd
const findLikeByUserIdAndPostId = async (userId, postId) => {
    return await Like.findOne({
        where: { userId, postId }
    });
};
```

### 조치 사항
- 각각의 코드를 비교 후 `raw: true` 코드의 유무 차이라고 판단.
- `raw:true`는 sequelize data, virtual data 없이 DB의 data만 깔끔하게 출력하는 sequelize ORM option.
- 하지만 boolean data 형에서는 mysql DB상에 tinyInt로 저장되어 있으므로 저장된 그대로인 0 또는 1 값을 반환.
- `raw: true`를 삭제 후 코드 변경.

```cmd
const findPostDetailWithLikeStatus = async (postId, userId) => {
    const post = await Post.findOne({
        where: { postId },
        attributes: { exclude: ['gender'] },
        include: [
            {
                model: Like,
                where: { postId, userId },
                attributes: ['likeStatus']
            }
        ]
    });

    return post;
};
```
![image](https://user-images.githubusercontent.com/109029407/189291650-b3ef5e1d-cd5f-489d-9e84-9c7ccef9400e.png)

- 참고자료 : https://javascript.plainenglish.io/why-you-should-be-cautious-with-sequelize-raw-options-5aaae9fc3ebd 

### 환경 설정

```cmd
OS: windows 10
Node: 16.15.1(kwanyung) 16.16.0(sumin-dev, subeom-lee)
npm : 8.13.2(kwanyung), 8.1.1(sumin-dev, subeom-lee)
```

**Comment by kwanyung** [comment]
raw : true 가 db에 있는 값을 그대로 보여주기 때문에 1, 0이라는 숫자가 그대로 출력된다는 것을 알았네요! raw : true 가 편리하긴 해도 include 와 같이 쓰면 까다로워 지는 등, 단점이 명확한 것 같아요.
