### ISSUE TITLE
DOCS : hotPosts(인기글) 지정 방식 알고리즘에 대한 고찰

### ISSUE THREAD

**Issue by sumin-dev** [moodCatcherProject/Back-End#108]
### 구현 API 목표

- 전날 받은 Like의 수가 가장 많은 게시물 1위부터 3위를 뽑아 메인페이지의 오늘의 hotPosts(인기글)에 게시.

### 고려해야할 점
- hotPosts는 **실시간 반영이 아닌 하루 단위로 변동**되므로 조회할 때마다 새로운 게시물로 바뀌면 안됨.
  => **HotPost 테이블을 따로 만들어** postId와 imgUrl을 저장해두고 매일 자정에 새로운 게시물로 data  교체(ERD 아직 미반영)
- 현재 Posts table에는 **likeCount가 있지만 누적되어 쌓인 like 수**를 나타내므로 하루 동안 받은 like를 산출하기에는 부적절.
  => Like 테이블의 **createdAt를 이용**하여 해당 날짜에 생성된 like 수를 세기. 
- **Like를 눌렀다가 취소하는 경우**도 반영되어야 함. 하루단위로 Like를 다시 체크하므로 유저가 매일 Like 등록과 취소를 반복하게 되면 인기글에 반복적으로 올라갈 수 있는 허점 발생.  
  => Like 등록 후 취소할 때 db를 delete하는 것이 아닌 **update 방식**으로 기록. Like 테이블에 **likeStatus 칼럼을 만들어 like를 누른 상태면 true, 취소하면 false로 변경**. 추후 다시 누르더라도 createdAt은 변경되지 않으므로 이를 토대로 신규등록한 like를 구별가능.
- **유저가 탈퇴하거나 게시글을 삭제**해도 인기글로 지정됐다면 메인페이지의 hotPosts에는 img가 보여야 함.
  => **유저탈퇴 시** 인기글 노출을 위해 하루정도 유저의 게시글 정보를 서비스에서 저장 후 삭제된다고 **고지하고 동의받기**
  => **게시글 삭제 시**에도 인기글로 지정된 경우 메인페이지에 img는 노출된다고 **고지하고 동의받기**
  => 메인페이지의 img를 눌렀을 때 해당 게시글의 **상세페이지**로 이동하면 **삭제된 게시물이라고 알림**띄우기
  => 게시글이 삭제되면 S3 버킷에 저장되어 있던 imgUrl도 같이 삭제되므로 **인기글 지정 시 imgUrl은 S3 버킷에 따로 저장** 후 인기글 교체될 때 버킷에서도 삭제
- **인기글 3개에는 중복된 유저가 없도록** 조건문으로 자격 확인할 것.
  
   ![dr](https://user-images.githubusercontent.com/109029407/189349395-5615650b-ea28-4eb2-a16b-2d1e1c2daa7a.png)

#### 1안
1) 익일 자정에 node-scheduler를 이용해 Like 테이블에서 **likeStatus가 true**이고 **createdAt이 어제**인 data 반환
```cmd
const findTodayLike = async () => {
    return await Like.findAll({
        where: {
            likeStatus: true,
            createdAt: {
                [Op.lt]: new Date(new Date() - 24 * 60 * 60 * 1000),
                [Op.gt]: new Date(new Date() - 48 * 60 * 60 * 1000)
            }
        },
        order: [['createdAt', 'DESC']],
        raw: true
    });
};
```

2) 받아온 data를 **map함수를 이용**해 postId만 뽑아 배열 형태로 만들기
```cmd
const findHotPosts = async () => {
    const todayLike = await likeRepository.findTodayLike();

    const hotPost = todayLike.map((like) => {
        return like.postId;
    });
    console.log(hotPost);
```
- **콘솔창**
 ```cmd
[
  3, 2, 5, 5, 3,
  2, 4, 2, 2, 4
]
```
3) **reduce함수를 이용**하여 배열을 돌며 최빈값 순서대로 뽑아내는 객체 만들기(postId가 key, 개수가 value)
  - 참고자료 : [자바스크립트 최빈값 구하기](https://velog.io/@minew1995/JavaScript-%EC%B5%9C%EB%B9%88%EA%B0%92-%EA%B5%AC%ED%95%98%EA%B8%B0) 
```cmd
    let check = hotPost.reduce((total, now) => {
        total[now] = (total[now] || 0) + 1;
        return total;
    }, {});
    console.log(check);
```
- **콘솔창**
 ```cmd
{ '2': 4, '3': 2, '4': 2, '5': 2 }
```
4) 객체에서 순서대로 **3개의 key를 뽑아** HotPosts 테이블에 postId와 imgUrl 저장
- 참고자료 : [객체에서 키값 가져오기](https://extbrain.tistory.com/32)
```cmd
    await postRepository.createHotPost(Object.keys(check)[0]);
    await postRepository.createHotPost(Object.keys(check)[1]);
    await postRepository.createHotPost(Object.keys(check)[2]);
```
#### 1안의 단점
- 유저가 늘어나면서 게시물이 늘어나고, 좋아요가 100개, 1000개로 늘어나게 되면 하루단위의 좋아요 최빈값을 구하기 위해 reduce 함수로 배열을 돌 때 비효율적. **최빈값 3개를 뽑기 위해 전체 게시물의 좋아요를 뽑아 postId별로 합산하여 세는 방식은 시간적으로도 DB 성능적으로도 좋지 못한 방법**이라 판단하여 2안으로 알고리즘 변경. 

#### 2안
1) Posts 테이블에 누적 좋아요 수인 likeCount 외에 **하루 단위의 좋아요 수인 todayLikeCount 칼럼**을 생성.
2) 유저가 like를 누를 때 **likeCount와 todayLikeCount를 같이 증가**. 취소 시에도 같이 감소시켜주기.
3) 익일 자정이 되면 **todaylikeCount로 순서정렬**하여 제일 높은 게시물 3개만 HotPosts 테이블에 저장.
4) **todayLikeCount는 매일 리셋**.
  - 참고자료 : [특정 컬럼의 모든  데이터 삭제하기](https://iwordpower.com/clear-all-data-from-a-single-column-in-mysql/)

### 환경 설정

```cmd
OS: windows 10
Node: 16.15.1(kwanyung) 16.16.0(sumin-dev, subeom-lee)
npm : 8.13.2(kwanyung), 8.1.1(sumin-dev, subeom-lee)
```

**Comment by kwanyung** [comment]
단순할 줄 알았는데 생각보다 인기글 알고리즘을 만드는게 쉽지 않네요. 많은 고민 해주신게 보여 보기 좋습니다!
