### ISSUE TITLE
DOCS : jest 테스트 코드 작성

### ISSUE THREAD

**Issue by kwanyung** [moodCatcherProject/Back-End#11]

**Comment by kwanyung** [comment]
.set('authorization', `Bearer ` + token) : 헤더에 데이터를 실을 수 있게 해줍니다.
.attach('postImage', 'test/testPicture.jpg') multy-form 데이터를 실을 수 있게 해줍니다.

**Comment by sumin-dev** [comment]
<테스트코드 Url query 적용법>

1) 일반적인 경우 url + query문
.get(`/api/auth/checkNickname?nickname=${'1'}`)

2) 한글의 경우 읽지 못하는 에러가 발생하므로 url과 query문을 각각 기재
.put('/api/users')
.query({ nickname: '주디', age: '10대', gender: '남자' })

**Comment by sumin-dev** [comment]
**.expect(400, done)** 과 **.expect(400).end((err,res) => {console.log(err) done()}** 은 차이가 있는 것 같습니다.
전자를 사용하면 status Code가 400이 아닐 경우 테스트가 **실패**했다고 알려주지만
후자를 사용하면 status Code가 400이 아니어도 콘솔창을 찍으며 테스트가 **성공**했다고 나옵니다.

혹시 원인을 아시나요?

조금 더 정확한 테스트를 위해서는 **전자로 형식을 통일**하고 에러내용 또는 응답내용이 궁금할 때만 후자를 사용해 테스트 코드를 돌려야 할 것 같습니다T.T

**Comment by subeom-lee** [comment]
테스트코드 잘 알려주셔서 감사합니다.
