### ISSUE TITLE
DOCS : Comment 댓글 조회

### ISSUE THREAD

**Issue by subeom-lee** [moodCatcherProject/Back-End#114]
### **구현 API 목표**

- 댓글 조회시 게시물 1개에 대한 유저 정보를 포함한 댓글과 유저 정보를 포한한 대댓글을 1페이지에 8개씩 보여준다.

### 요구사항

![ERD](https://user-images.githubusercontent.com/108959585/189583176-f5855929-31ea-4f7c-8ba9-4dc9d3ec18c6.PNG)

- ERD에 Comment테이블과 Recomment테이블과 User테이블이 userId로 모두 연결되어있고 Comment테이블과 Recomment테이블은 commentId로 연결되어있다.

**댓글을 조회 할 때 보여줘야하는것들**

- 해당 게시물 대한 댓글들을 페이지네이션을 통해 1페이지에 8개의 댓글을 보여준다.
- 댓글의 정보(userId, commentId, content, createdAt)
- 댓글을 작성한 작성자의 정보(nickname, imgUrl, grade)
- 댓글에 달린 대댓글이 있다면 그 대댓글의 정보(userId, recommentId, content, createdAt)
- 대댓글을 작성한 작성자의 정보(nickname, imgUrl, grade)

### 구현 방법

1. Comment테이블에서 페이지네이션을 하고 해당 postId로 findAll한다.
2. Comment에서 User와 include하여 해당 유저의 정보를 attributes한다.
3. Comment에서 Recomment와 include하여 해당 대댓글의 정보를 attributes한다.
4. Comment에서 Recomment를 include한것에 User와 include하여 해당 대댓글의 유저정보를 attributes한다.

```
const getComments = async (postId, page, count) => {
    const getComments = await Comment.findAll({
        where: { postId },
        offset: count * (page - 1),
        limit: count,
        attributes: ['userId', 'commentId', 'content', 'createdAt'],
        include: [
            {
                model: User,
                attributes: ['nickname', 'imgUrl', 'grade']
            },
            {
                model: Recomment,
                attributes: ['userId', 'recommentId', 'content', 'createdAt'],
                include: [
                    {
                        model: User,
                        attributes: ['nickname', 'imgUrl', 'grade']
                    }
                ]
            }
        ]
    });
    return getComments;
};
```

- findAll로 받은 배열로 된 정보들을 map을 통하여 모두 정렬해준다.
1. Comment정보와 Comment의User정보를 map을 돌린다.
2. Comment에대한 Recomment의 정보와Recomment의User정보를 map을 돌린다.

```
const getComments = async (postId, page, count, userId) => {
    const getComments = await commentRepository.getComments(postId, page, count, userId);
    data = getComments.map((e) => e.get({ plain: true }));

    const post = await postRepository.findPost(postId);
    if (post === null) {
        throw new exception.BadRequestException('게시물 없음.');
    }

    return data.map((f) => {
        return {
            userId: f.userId,
            commentId: f.commentId,
            content: f.content,
            nickname: f.User.nickname,
            imgUrl: process.env.S3_STORAGE_URL + f.User.imgUrl,
            grade: f.User.grade,
            createdAt: f.createdAt,
            recommentId: f.Recomments.map((a) => {
                return {
                    userId: a.userId,
                    recommentId: a.recommentId,
                    content: a.content,
                    nickname: a.User.nickname,
                    imgUrl: process.env.S3_STORAGE_URL + a.User.imgUrl,
                    grade: a.User.grade,
                    createdAt: a.createdAt
                };
            })
        };
    });
};
```

### **이 기능을 구현하며 배운 점**
이 기능을 구현하기 전에는 include나map에 대해 정확히 알지 못하고 조금씩 사용해봤던 정도였는데,<br>이 기능을 구현하게 되면서 include와 map의 기능을 더 자세히 알게 된 것 같다.

**Comment by kwanyung** [comment]
참조한 테이블에서 외래키로 다시 참조하는 게 쉽지 않았을 것 같은데 고생하셨습니다! 댓글과 대댓글을 합쳐 8개만 출력해주는 것 같은데 맞나요?

**Comment by subeom-lee** [comment]
댓글만 8개 보여주고 대댓글은 계속 보여줍니다!

**Comment by sumin-dev** [comment]
제일 참조를 많이 한 테이블인 것 같습니다. 2개 이상의 테이블을 include를 사용할 때 sequelize 사용법을 덕분에 알게되었습니다. 고생하셨습니다!
