### ISSUE TITLE
BUG : blocked by CORS policy 해결기

### ISSUE THREAD

**Issue by sumin-dev** [moodCatcherProject/Back-End#138]
### 한 일
- passport와 session을 이용해 카카오 소셜로그인 및 로컬로그인 구현
  - 사용자가 로그인을 하면 세션에 유저의 정보가 저장되고 유저 정보를 압축한 쿠키를 브라우저에 보냄
  - 이후 모든 요청에서 브라우저에서 쿠키를 보내주면 서버에서 해당 쿠키를 세션과 비교 조회하여 유저의 모든 정보를 불러와서 브라우저로 다시 보내주는 과정 
- Thunder client, Insomnia 등으로 로그인 API 테스트를 했을 때는 문제없이 진행되는 부분이 브라우저와 직접 통신 시에는 CORS 에러 발생.

### 에러 내용
---
**try 1)** 서버측 응답 헤더에 `res.header('Access-Control-Allow-Origin', '*');` 설정

- **에러발생** 
Access to XMLHttpRequest at 'http://localhost:3000/?exist=false&cookie=[object%20Object]' (redirected from 'http://서버주소/api/auth/login%27) from origin 'http://localhost:3000/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

- **원인**
CORS 정책 상 `Access-Control-Allow-Origin`이 wildcard(*)일 경우 Origin의 제한 없이 요청하고 결과를 읽을 수 있지만, 인증 정보가 포함된 경우에는 쿠키를 제거하고 요청하도록 정책이 구성되어 있어서 인증 정보를 포함한 요청에서는 불가능.
참고 : [CORS 쿠키 전송하기](https://inpa.tistory.com/entry/AXIOS-%F0%9F%93%9A-CORS-%EC%BF%A0%ED%82%A4-%EC%A0%84%EC%86%A1withCredentials-%EC%98%B5%EC%85%98)
---
**try 2)** 브라우저와 서버 corsOptions에 `credentials: true` 옵션 추가

- **에러발생**(try 1과 동일 에러 메세지)
Access to XMLHttpRequest at 'http://localhost:3000/?exist=false&cookie=[object%20Object]' (redirected from 'http://서버주소/api/auth/login%27) from origin 'http://localhost:3000/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute. 

- **원인**
`credentials:true` 옵션 추가시 origin을 와일드카드(*)로 설정할 수 없음. `Access-Control-Allow-Origin`에 정확한 브라우저 주소를 기재해야 함. 
---
**try 3)** origin에 *이 아닌 브라우저 주소 `http://localhost:3000` 설정

- **에러발생**(상동)
-  **원인**
알 수 없는 이유로 지속적인 CORS 에러 발생
---
### 조치 사항
- 구글링을 통해 해결해보고자 했지만 상황을 타개할만한 자료를 찾을 수 없었고, session 방식에 대한 이해 부족과 한정된 시간 때문에 단기적으로 CORS 해결이 어려울 것으로 판단. 매우 아쉽지만 쿠키로 인증 정보를 전달하는 session 로그인 방식에서 토큰을 전달하는 jwt 로그인 방식으로 변경 결정(jwt 로그인 시에는 CORS 에러 발생X)
- 비록 CORS 에러를 해결하지 못했지만 차후 프로젝트에서 세션쿠키 방식 로그인 구현을 위해 Git issue 기록 #139 

### 환경 설정

```cmd
OS: windows 10
Node: 16.15.1(kwanyung) 16.16.0(sumin-dev, subeom-lee)
npm : 8.13.2(kwanyung), 8.1.1(sumin-dev, subeom-lee)
```

**Comment by kwanyung** [comment]
이때 뽑은 머리카락만 한 주먹은 될 것 같네요.. 보안을 위해 존재하는 CORS가 저희같은 초보 개발자에게는 벽처럼 느껴지는게 아이러니 하네용.

**Comment by subeom-lee** [comment]
CORS는 까도까도 어렵고 난해하네요 CORS를 마스터할때까지 열심히 같이 달려봅시다! 좋은 정보글 감사합니다.
