### ISSUE TITLE
DOCS : CORS란 무엇인가?

### ISSUE THREAD

**Issue by sumin-dev** [moodCatcherProject/Back-End#139]
### CORS 개념
- Cross Origin Resource Sharing
- CORS 정책은 우리가 가져오는 리소스들이 안전한지 검사하는 관문
- 웹에는 크게 SOP(Same Origin Policy)와 CORS(Cross Origin Resource Sharing) 두가지 정책이 있음
  - **SOP(동일 출처 정책)** : `같은 출처에서만 리소를 공유할 수 있다` 라는 규칙을 가진 정책 
    - URL의 구성요소 중 프로토콜, 호스트, 포트가 동일하면 다른 요소는 다르더라도 Same Origin으로 인정. 이들 중 하나라도 일치하지 않으면 Cross Origin이 되어 브라우저는 교차 출처 요청을 실행
   ![image](https://user-images.githubusercontent.com/109029407/190170225-05a3ab2b-5a0a-4d1c-8377-f8da317101e5.png)

  - **CORS(교차 출처 리소스 공유)** : 추가 HTTP 헤더를 사용하여 한 출처에서 실행 중인 웹 어플리케이션이 다른 출처의 선택한 자원에 접근할 수 있는 권한을 부여하도록 브라우저에 알려주는 체제
    - 프론트엔드 서버와 백엔드 서버가 별도로 존재하는데 만일 프론트서버 URL이 `http://localhost:3000`이고 백엔드 서버가 `http://localhost:8080`에 띄워져 있으면 둘은 서로 다른 출처이므로 SOP 정책에 어긋나기 때문에, 서버로부터 응답이 넘어올 때 브라우저에서 CORS Policy 오류를 발생시킴
    ![image](https://user-images.githubusercontent.com/109029407/190171776-b56e10a8-ca65-4cb1-a6b1-9f34a3fbbf6c.png)

#### 1. 클라이언트에서 HTTP 요청의 헤더에 Origin을 담아 전달
![image](https://user-images.githubusercontent.com/109029407/190173331-495501c2-9781-43de-ab5d-275acea63d3d.png)
#### 2. 서버는 응답헤더에 Access-Control-Allow-Origin을 담아 클라이언트로 전달
![image](https://user-images.githubusercontent.com/109029407/190173688-4cc699d7-4b9b-468f-931c-8a37db3e0184.png)
#### 3. 클라이언트에서 자신이 보냈던 요청의 Origin과 서버가 보내준 Access-Control-Allow-Origin을 비교하여 차단 여부를 결정하는데 유효하지 않다면 서버의 응답을 사용하지 않고 버림
- CORS 정책에 의해 Origin을 비교하는 로직은 브라우저에 구현되어 있음
- 브라우저가 CORS 정책 위반을 분석하는 시간은 서버의 응답이 도착한 이후
- 서버에서 정상적인 응답을 하여 Status Code가 200이 나오더라도, 브라우저가 응답을 CORS 정책 위반이라고 분석하면 그 응답은 사용하지 않음

#### 서버에서 Access-Control-Allow-Origin 세팅하기
```cmd
res.setHeader('Access-Control-Allow-origin', '*'); // 모든 Origin 허용
res.setHeader('Access-Control-Allow-Credentials', 'true'); // 쿠키 주고받기 허용
```
- *(와일드카드)을 사용하면 모든 Origin에서 오는 요청을 허용한다는 의미
- 보안 상 좋지 않기 때문에 출처를 직접 명시해줄 것
```cmd
res.setHeader('Access-Control-Allow-origin', 'https://서버주소.com');
```
- Access-Control 설정 종류
```cmd
// 헤더에 작성된 출처만 브라우저가 리소스를 접근할 수 있도록 허용함.
Access-Control-Allow-Origin: "https://서버주소.com"
 
// 리소스 접근을 허용하는 HTTP 메서드를 지정해 주는 헤더
Access-Control-Request-Methods: GET, POST, PUT, DELETE 
 
// 서버에서 응답 헤더에 추가해 줘야 브라우저의 자바스크립트에서 헤더에 접근 허용
Access-Control-Expose-Headers: Authorization 
 
// preflight 요청 결과를 캐시 할 수 있는 시간을 나타냄.
// 60초 동안 preflight 요청을 캐시하는 설정으로, 첫 요청 이후 60초 동안은 OPTIONS 메소드를 사용하는 예비 요청을 보내지 않는다.
Access-Control-Max-Age: 60 
 
// 자바스크립트 요청에서 credentials가 include일 때 요청에 대한 응답을 할 수 있는 지를 나타낸다
Access-Control-Allow-Credentials: true
```
### 자료 출처
- [CORS 개념, 해결방법](https://inpa.tistory.com/571)
- [Axios CORS 해결하기](https://inpa.tistory.com/entry/AXIOS-%F0%9F%93%9A-CORS-%EC%BF%A0%ED%82%A4-%EC%A0%84%EC%86%A1withCredentials-%EC%98%B5%EC%85%98)
- [Node.js CORS 해결하기](https://inpa.tistory.com/entry/NODE-%F0%9F%93%9A-CORS-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0-cors-%EB%AA%A8%EB%93%88)

**Comment by kwanyung** [comment]
CORS 정책으로 Origin을 비교하는 정책이 브라우저에 있으니 썬더 클라이언트로는 이상이 없었군요..! 서버의 응답헤더를 확인하는 과정을 거치는 것이니 서버측에서는 헤더에 Access-Control-Allow-origin 값을 유효하게 넣어주면 되는 것이였군요. app.user(cors()) 정도 쓰면 되겠지 싶었는데 수민님 덕분에 CORS에 대해 조금 더 알아가는 것 같습니다. 감사합니다!

**Comment by subeom-lee** [comment]
CORS 정보 감사합니다. 덕분에 CORS에 대한 많은 정보를 간단하게 얻어갑니다.
