### ISSUE TITLE
DOCS : 여러모로 활용 가능한 aws lambda 이야기(이미지 리사이징)

### ISSUE THREAD

**Issue by kwanyung** [moodCatcherProject/Back-End#203]
aws lambda??
============
lambda는 aws에서 특정 상황을 설명 해 주는 트리거를 이용해 실행하는 함수입니다. 
![1  검색페이지](https://user-images.githubusercontent.com/71562311/192084563-811519d0-d0f1-4792-89c6-7d1c3e37daff.PNG)

aws에서 lambda 를 검색해서 

![2  함수 생성](https://user-images.githubusercontent.com/71562311/192084595-06ae7d20-fd6e-4bc7-8359-f5e9341faf48.PNG)

우측 상단의 함수 생성을 클릭해 새로운 함수를 생성 할 수 있습니다. 

![3  리사이징](https://user-images.githubusercontent.com/71562311/192084622-af896abf-aabf-4ed4-84a0-b49e398d80aa.PNG)

저는 s3ImageResizing이란 함수를 만들어 S3에 새로운 사진이 들어올 때 마다 함수가 실행되도록 설정했습니다.

조금 더 자세히 설명을 드려 볼게요.

trigger?
----------
트리거란 총의 방아쇠라는 뜻을 가지고 있습니다. 방아쇠를 당기면 총알이 나가는 것 처럼 lambda에서 트리거를 당기면 함수를 실행하는 것이고 트리거를 당길 조건을 설정하는 것이 트리거 추가 라고 보실 수 있겠습니다.

S3말고도 많은 트리거를 추가할 수 있으니 여러모로 활용이 가능해 보입니다.

이미지 리사이징?
--------------------

![1663585433130](https://user-images.githubusercontent.com/71562311/192085002-6effe7ab-c988-4dce-8793-86f80d4c359f.jpg)

![1663586380490 (1)](https://user-images.githubusercontent.com/71562311/192085056-294c6d91-0f2c-4845-9acc-90b3c0d587db.jpg)

민망하지만 저의 사진으로 이미지 리사이징을 시도했습니다.

![원본사진 정보](https://user-images.githubusercontent.com/71562311/192085162-984029b6-1730-40ef-a3c9-1aacb09e5d9e.PNG)![리사이징 사진 정보](https://user-images.githubusercontent.com/71562311/192085173-4fc4c760-ed10-41fc-a202-a632e609b1d7.PNG)

왼쪽은 원본사진, 오른쪽은 리사이징 된 사진의 정보들입니다. 
확연한 차이가 눈에 띄시나요?

이미지의 크기, 그리고 파일크기의 차이가 보이실 겁니다. 
원본은 198kB, 리사이징 된 사진의 크기는 10.6kB인데 

## 약 19배정도의 파일크기 차이를 가지는 것을 확인 할 수 있네요!

참고로 무드캐처의 메인페이지 이미지를 넣는 박스는 140 185 의 크기를 가지고 있습니다.

처음 시도때는 140 px을 기준으로 사진을 축소 했었는데..

![1663585067383 (2)](https://user-images.githubusercontent.com/71562311/192085423-94d69e36-965f-4438-bc04-9a1b19c03e75.jpg)

보시다시피 유저 경험에 치명적일 정도의 화질을 보여주네요!

여러가지 사진으로 테스트를 해본 결과 현재는 280px을 기준으로 이미지 리사이징을 진행하고 있습니다. 

이미지 리사이징을 진행하고 나서는 눈에 띌 정도로 화면이 빠르게 랜더링 되는 것이 보였습니다!

그렇다면 왜 굳이 lambda를 이용할까요?
----------------------------------------------
저희는 multer를 이용해 서버에서 이미지 리사이징을 진행 할 수도 있고 프론트에서 파일을 리사이징 해서 보내줄 수도 있을 겁니다.
하지만 굳이 lambda를 이용했는데요. 이는 Serverless 라는 개념을 사용하기 위해서 입니다.

서버리스.. 서버가 없다? 라고 생각하실 수 있겠지만 이는 서버가 없는 것이 아니라 특정 작업을 수행하기 위해 컴퓨터를, 혹은 가상 머신에 서버를 설정하고 이를 통해 작업을 처리해주는 것을 서버리스라고 합니다.

multer를 이용해서 이미지를 리사이징 하는 것은 시간도 오래 걸릴 뿐만 아니라 서버의 한정된 자원을 소모하기 때문에 서버가 느려지는 원인이 될 수도 있습니다.

부하 직원에게 일을 맡기면 상사는 다른 일을 할 수 있게되니 aws에 일처리를 부탁한다는 느낌으로 이해할 수 있겠습니다.

그래서 lambda를 어떻게 사용할까요?
--------------------------------------------
![람다 폴더](https://user-images.githubusercontent.com/71562311/192087668-32404bc5-84db-4e6c-ab33-053e02c3a529.PNG)

우선 lambda 에는 실행할 파일을 넣어 주어야 합니다. 
이때 기본적으로 package.json등 코드를 실행해주는 파일들이 없기 때문에 폴더를 하나 만들고 그 안에 npm init 등을 활용해 package.json을 만들어 주어야 합니다. 물론 라이브러리도 다운을 받아줘야 하구요.

실행할 코드는 index.js 안에 넣습니다.

```
const sharp = require('sharp');
const aws = require('aws-sdk');
const s3 = new aws.S3();

const transformationOptions = [{ name: 'w280', width: 280 }];

exports.handler = async (event) => {
    try {
        const Key = event.Records[0].s3.object.key;
        const keyOnly = Key.split('/')[1];
        console.log(`image Resizing : ${keyOnly}`);
        const image = await s3.getObject({ Bucket: '버킷 이름', Key }).promise();
        await Promise.all(
            transformationOptions.map(async ({ name, width }) => {
                try {
                    const newKey = `${name}/${keyOnly}`;
                    const resizedImage = await sharp(image.Body).rotate().resize(width).toBuffer();
                    await s3
                        .putObject({ Bucket: '버킷 이름', Body: resizedImage, Key: newKey })
                        .promise();
                } catch (err) {
                    throw err;
                }
            })
        );

        const response = {
            statusCode: 200,
            body: event
        };
        return response;
    } catch (err) {
        console.log(err);
        return {
            statusCode: 500,
            body: err
        };
    }
};
```
위는 w280이라는 버킷의 폴더 안에 (없다면 새로 만듭니다) 280px 을 기준으로 리사이징 한 사진을 넣는 코드입니다.

## 이후 폴더를 압축해 주셔야 합니다.
=> 압축을 하게되면 파일이 9~10MB 정도 크기를 가집니다. 10MB를 넘어가면 s3를 통해 업로드를 해주어야 하기 때문에 귀찮아 지고 아래 사진과 같이 .zib 파일을 lambda에 업로드 할 수 있기 때문입니다.

![7  업로드](https://user-images.githubusercontent.com/71562311/192087715-978d4062-422b-4d06-b498-a73aedaf5d30.PNG)

이후 ~에서 업로드 =>.zip 파일 을 클릭해 파일을 업로드 하고

사진의 '모니터링' 이라는 부분에서 로그를 확인해 사진의 리사이징이 잘 적용 되는지 확인할 수 있습니다.

이제 lambda, trigger, 파일 업로드 하는 방법 등을 확인했으니 이미지 리사이징 말고 다른 분야에서도 꼭 활용해 봤으면 좋겠네요!

**Comment by sumin-dev** [comment]
<람다 사용하기> 미니북 출간하셔도 될 것 같습니다. 자세히 기술해주셔서 이해가 잘되네요! 저희 프로젝트는 패션 커뮤니티 앱이라 사진이 주가 되는 서비스인데, 사진이 고화질일수록, 용량이 커질수록, 개수가 많아질수록 브라우저에서 로딩하는 시간이 길어지는 문제가 발생했을 겁니다T.T 람다를 사용한 이미지 리사이징은 획기적인 기술 도전이네요! 람다의 활용 가능성을 알게 된 것도 좋네요. 덕분에 배워갑니다! ^______^

**Comment by taesikyoon** [comment]
개 추 2

**Comment by subeom-lee** [comment]
람다를 이용한 이미지 리사이징은 엄청 많이 쓰이는 기술같은데 이 기회에 많이 배워갑니다
