### ISSUE TITLE
DOCS : MYSQL 테이블 변경 명령어 정리

### ISSUE THREAD

**Issue by sumin-dev** [moodCatcherProject/Back-End#273]
# ✔DOCS를 작성하게 된 배경
- 서비스 배포 2일차, 유저에게 피드백이 왔는데 MYSQL DB 모델 및 마이그레이션이 변경되어야 하는 부분이 있었다.
- 배포 전 개발환경에서 DB를 수정할 때는 아래의 코드를 활성화했다.
```cmd
            sequelize
                .sync({ force: true })
                .then(() => {
                    console.log('데이터베이스 연결 성공');
                })
                .catch((err) => {
                    console.error(err);
                });
```

- 서비스 배포 후 유저 데이터가 100명 가까이 쌓인 지금, 저 코드를 사용하면 DB 구조는 바뀌겠지만, data도 예쁘게 삭제될 것이다.
- 고심하면서 API 명세서를 작성하고 ERD를 작성해도 서비스를 업데이트 하면서 DB 구조가 바뀌는 일은 불가피한 것 같다.
- MYSQL 명령어를 통해 DB 수정을 성공적으로 마치고, 언젠가 찾아올 다른 업데이트를 위해 기록을 남긴다.

# ✔MYSQL 테이블 변경 절차
#### 2️⃣ MYSQL 확장 프로그램에서 명령어로 DB 변경
![image](https://user-images.githubusercontent.com/109029407/193419178-4cd2d3f1-5977-4ccb-a3c4-81337f234cbd.png)
#### 4️⃣ 서버 PM2 재가동 

# ✔MYSQL 테이블 변경 명령어 정리
#### 🔹 테이블 컬럼 추가(맨 뒤)
```cmd
ALTER TABLE [테이블명] ADD [컬럼명] [자료형]
예시) ALTER TABLE Items ADD url varchar(255)
```

#### 🔹 테이블 컬럼 추가(디폴트 값 설정_디폴트설정 안하면 초기값 null)
```cmd
ALTER TABLE [테이블명] ADD [컬럼명] [자료형] DEFAULT [디폴트 값]
예시) ALTER TABLE Auths ADD isExistsMap boolean DEFAULT false
```

#### 🔹 테이블 컬럼 추가(맨 앞)
```cmd
ALTER TABLE [테이블명] ADD [컬럼명] [자료형] FIRST
예시) ALTER TABLE Items ADD url varchar(255) FIRST
```

#### 🔹 테이블 컬럼 추가(지정 컬럼 다음)
```cmd
ALTER TABLE [테이블명] ADD [컬럼명] [자료형] AFTER [앞컬럼명]
예시) ALTER TABLE Items ADD url varchar(255) AFTER brand
```

#### 🔹 테이블 컬럼 삭제
```cmd
ALTER TABLE [테이블명] DROP [컬럼명] 
예시) ALTER TABLE Items DROP url 
```

#### 🔹 테이블 컬럼명 변경
```cmd
ALTER TABLE [테이블명] CHANGE [기존컬럼명] [새컬럼명] [기존자료형]
예시) ALTER TABLE Items CHANGE url imgUrl varchar(255)
```

#### 🔹 테이블 컬럼 자료형 변경
```cmd
ALTER TABLE [테이블명] CHANGE [컬럼명] [컬럼명] [새자료형]
예시) ALTER TABLE Items CHANGE url url int
```

**Comment by kwanyung** [comment]
production db를 건드는 건 언제나 두려워요.. my sql 문법을 배우는 건 중요하죠.

**Comment by subeom-lee** [comment]
수민님덕분에 my sql문법으로 DB를 신중하게 사용할수 있었습니다 ^_^
