### ISSUE TITLE
DOCS : Node.js에서 웹 크롤링하기(무신사)

### ISSUE THREAD

**Issue by sumin-dev** [moodCatcherProject/Back-End#48]
### 크롤링(Crawling)이란?

- 웹 크롤링(Web crawling)의 정식 명칭은 **Web Scraping**
- 웹 사이트에서 데이터를 가져오는 것

#### Axios 
- 브라우저와 Node 환경에서 사용하는 Promise 기반의 HTTP 비동기 통신 라이브러리
- 사이트의 HTML을 가져올 때 사용
#### Cheerio 
- Node.js 환경에서 JQuery처럼 DOM Selector 기능들을 제공
- Axios의 결과로 받은 데이터에서 필요한 데이터를 추출하는데 사용하는 라이브러리

#### 라이브러리 설치
```
npm -i --save axios cheerio
```
#### 추출할 데이터 정하기
- 무신사 홈페이지 검색창에 `운동화` 검색
- 추출할 데이터에서 `마우스 우클릭` - `검사`
![image](https://user-images.githubusercontent.com/109029407/188276600-ffd5817a-d6b4-4979-8c6c-0c2a64597396.png)

- 개발자도구 창의 요소에서 추출할 `HTML의 태그 이름`과 `Class 이름` 목록을 정리
![image](https://user-images.githubusercontent.com/109029407/188276786-b4e1e83c-242a-4c4e-8844-6607781b9571.png)

```
<div class="list-box box">
<div>
<ul class="snap-article-list boxed-article-list article-list center list goods_small_media8" id="searchList">
<li class="li_box">

```
- **list-box**라는 class 안의 **div** 태그 안의 **ul** 태그에서 **li_box**라는 class 이름을 가진 li 태그들의 데이터를 추출
- 이미지파일, 브랜드명, 상품명, 가격 각각의 요소를 검사해서 자료 하나하나 인자 뽑기
![image](https://user-images.githubusercontent.com/109029407/188278318-0019f2d6-d507-45aa-a611-0ee09c5ce040.png)

#### 코드 작성하기
```
const axios = require('axios');
const cheerio = require('cheerio');
const exception = require('../exceptModels/_.models.loader');

const crawlingMusinsa = async (keyword) => {
    const getHTML = async (keyword) => {
        try {
            return await axios.get(
                `https://www.musinsa.com/search/musinsa/goods?q=${encodeURI(
                    keyword
                )}&list_kind=small&sortCode=pop&sub_sort=&page=1&display_cnt=0&saleGoods=&includeSoldOut=&setupGoods=&popular=&category1DepthCode=&category2DepthCodes=&category3DepthCodes=&selectedFilters=&category1DepthName=&category2DepthName=&brandIds=&price=&colorCodes=&contentType=&styleTypes=&includeKeywords=&excludeKeywords=&originalYn=N&tags=&campaignId=&serviceType=&eventType=&type=&season=&measure=&openFilterLayout=N&selectedOrderMeasure=&shoeSizeOption=&groupSale=&d_cat_cd=&attribute=`
            );
        } catch (err) {
            console.log(err);
        }
    };
    const parsing = async (keyword) => {
        const html = await getHTML(keyword);

        const $ = cheerio.load(html.data);
        const $itemList = $('.li_box');

        let items = [];
        $itemList.each((idx, node) => {
            const brand = $(node).find('.item_title').text();
            const image = $(node).find('.list_img> a> img').attr('data-original');
            const price = $(node).find('.price').text();
            const title = $(node).find('.list_info>a').attr('title');

            items.push({
                brand,
                title,
                image: 'https:' + image,
                price: price.trim()
            });
        });
        
        return { items };
    };
    return await parsing(keyword);
};

module.exports = {
    crawlingMusinsa
};

```
#### 코드 설명
- getHtml 함수는 axios.get 함수를 이용하여 비동기로 html 파일을 가져옴
- 그 후 반환되는 Promise 객체에 cheerio를 이용하여 데이터 가공(반환된 객체에 이름을 붙일 때는 $를 사용)
- cheerio를 이용하면 JQuery처럼 특정 element 이름을 지정할 때 곧바로 찾아서 접근 가능
  - cheerio의 **load** : 인자로 html 문자열을 받아 cheerio 객체 반환
  - cheerio의 **each** : 인자로 콜백 함수를 받아 태그들의 배열을 순회하면서 콜백함수 실행
  - cheerio의 **find** : 인자로 html selector를 문자열로 받아 해당하는 태그를 반환
  - class를 가져올 때는 `$('.li_box')` id 값을 가져올 때는 `$('#li_box')`

### 참고자료
- [Node.js에서 웹 크롤링하기](https://velog.io/@yesdoing/Node.js-%EC%97%90%EC%84%9C-%EC%9B%B9-%ED%81%AC%EB%A1%A4%EB%A7%81%ED%95%98%EA%B8%B0-wtjugync1m)

**Comment by kwanyung** [comment]
막상 크롤링을 시도하면 못가져오는 데이터도 많으니 파이썬의 selenium 처럼 페이지를 직접 켜서 다루는 모듈도 필요할 지 모르겠어요.

**Comment by sumin-dev** [comment]
reply와 좋은 모듈 추천 감사합니다 권영님^0^
node.js 에서는 selenium-webdriver라는 모듈을 지원하는 군요!

무신사 크롤링을 했을 때(검색어: '운동화', '이불' 등) 데이터를 못가져오는 경우는 아직 발견하지 못했는데
만약 발생한다면 권영님의 말씀대로 selenium과 cheerio를 적용해야할 것 같습니다.

저희 add on 과제로 무신사 외에 크롤링 사이트를 추가하게 된다면 그때도 참고하여 진행하겠습니다~!
