### ISSUE TITLE
Post 데이터베이스 테이블에 관한 이야기입니다.

### ISSUE THREAD

**Issue by kwanyung** [moodCatcherProject/Back-End#49]
저희는 하루 단위로 좋아요 수를 집계하려고 구상을 하고 있는데 이를 위해서는 Post테이블에 accLike 같은 지금까지의 누적 좋아요를 기록할 수 있는 컬럼이 필요할 것 같아요.

그리고 createdAt로 오늘 받은 좋아요만 기록할 방법이 있을까요?
그리고 사용자가 좋아요를 취소했다가 다시 좋아요를 한다면 게시물에 한사람의 좋아요가 지속적으로 쌓일 것 같은데 어떻게 처리할 수 있을까요?

**Comment by sumin-dev** [comment]
1) 좋아요 집계수가 필요한 이유가 `moodPoint` 적립이나 `hotPosts`를 뽑기 위한 거라면 집계 즉시 `moodPoint`를 적립시키거나, 일주일치 좋아요를 집계 즉시 `hotPosts`를 뽑는 등 DB에 저장하지 않고 바로 결과를 반영하면 될 것 같습니다!
혹시 그날그날 단위의 좋아요 집계수를 누적 기록해야하는 이유를 여쭤봐도 될까요?!

2) 오늘 받은 좋아요만 기록할 방법은 오늘 날짜와 `createdAt`의 `연/월/일` 부분이 일치하는 data를 count하면 될 것 같습니다~!
예를 들어 2022년 9월 4일에 받은 좋아요 수를 뽑으려면 `createdAt`에 `2022-09-04`를 포함하는(뒤에 오는 시/분/초는 고려X) data를 찾아서 count하는 알고리즘이 좋을 것 같아요. 하루 단위로 집계한다고 했으니 9월 4일에서 9월 5일로 넘어가는 시점(ex. 9월 5일 12:01 a.m.)에 node scheduler를 사용하면 좋겠습니다

3) 한 개의 게시물이 가진 총 좋아요 수는 `좋아요`를 누를 때 `+1`, 다시 누르면 취소로 반영되어 `-1`이 되므로 한 사람이 같은 행위를 반복하는 것은 좋아요 수가 늘어나지 않을 것 같습니다. 제가 이해한 바가 맞을까요 권영님? ^0^
